### PR TITLE
Update miniTools.R

### PR DESCRIPTION
**Pull request by lecorguille**
Add `parseCommandArgs` which overwrite the default `batch::parseCommandArgs` to solve an issue with batch if arguments are logical TRUE/FALSE

### CODE REVIEW

**Comment by melpetera** [comment]
I totally forgot there were PRs here... So late :grimacing:
@lecorguille is this still topical?

**Comment by melpetera** [comment]
ping @lecorguille :slightly_smiling_face:

**Comment by lecorguille** [comment]
No idea :/

**Comment by melpetera** [comment]
I investigated a little. I think the best is to provide an alternative function instead of overwriting the previous. Indeed, this is meant to be part of a package in the end, and overwriting it may induce that people using the package for other functions may also have to adapt the way they chose to handle the "TRUE/FALSE" in their scripts. 

By making it a separated function, people can choose to use it or not, so when not needed they would not need to change anything. 

Ok for you @lecorguille 😺 ? (see 1ab6d30)

**Comment by lecorguille** [comment]
It's rather classic to overwrite a function but always disturbing.
So ok with you.

Have you try to run rlint, because I remember that it recommend to avoid uppercase in function name 😝

**Comment by melpetera** [comment]
Here I did not check rlint. 
It will be done sooner or later, but for now, having limited time and being very late, the objective is to settle ongoing codes as long as they are functional.
Thank you for your feedback 🙂

**Pull request merged**
