### PR TITLE
Add new helper methods for data frames.

### PR DESCRIPTION
**Pull request by pkrog**
Add df.force.numeric() method for converting integer columns of a data
frame to numeric type.
Add df.read.table() method for loading a data frame from a CSV file and
possibly converting integer columns to numeric.

@mtremblayfr you can use these methods to read directly your integer table and convert it into numeric:
```r
data <- df.read.table("probleme.tabular", header=TRUE, sep="\t", row.names=1, force.numeric = TRUE)
```

### CODE REVIEW

**Comment by melpetera** [comment]
Hi @pkrog 
I totally forgot there were PRs here... I am SO late :grimacing:
Do you think this PR is still topical?
I am not familiar with the test structure, but it seems all good to me.

**Comment by pkrog** [comment]
I don't remember exactly why I did this PR. I must have been answering a concern from you in one of our meetings.
If it is still relevant, please merge this PR.
The tests are ad hoc tests, since your package is not a standard R package. Would you like to transform this repository into a standard R package (possibly submitting it to CRAN or letting it inside GitHub only for installation through devtools::install_github())?

**Comment by melpetera** [comment]
Truth is I am back on this repository because I will finally begin the conversion to a standard R package (I was supposed to do it long ago but it was complicated to find time to do it - not that I have free time now, but it is so outdated that I can not continue postponing it without feeling terrible, so I'll try to free up time specially for that). 

The idea is to resolve on-going work before restructuring it to a "package format". I am not too familiar with test format for packages, but it seems it is possible to have a "tests" folder inside the package. Is the test folder you defined compatible with that? I do not know how the "Makefile" files work and if it can be kept as package files or not. I was planning to investigate that after resolving the on-going PR.

**Comment by pkrog** [comment]
I always use a Makefile inside an R package for my own purposes, but specify to ignore it when building or checking the package. So it's harmless.
The current tests will need to be updated in order to comply with the R package format. I can help you on that once you have started the refactoring into a package.
I suggest you merge that PR now, and I will join you later to help you on this part of the package. Contact me when you are ready.

**Comment by melpetera** [comment]
I will do as suggested. Thanks a lot!

**Review by melpetera — APPROVED** [review]

**Pull request merged**
